### PR TITLE
Separating bundle name connectivity status

### PR DESCRIPTION
**Pull request by pantelisss**
## **Why?**
Updated the "chips" area in stations screens
### **How?**
- Declared `StationBundle` to represent the bundle station object
- Removed `Profile` enum
- Added `bundle` property in device model (`PublicDevice`, `DeviceDetails`, `NetworkDevicesResponse`, `NetworkSearchDevice`)
- Updated search database models (`DBBundle`) for the persisted results in search screen
- Updated the station chips view
### **Testing**
- Make sure the chips view is rendered as expected
- Make sure nothing is broken in station screens (home, station details, station settings, explorer, search)
### **Additional context**
fixes fe-938

### CODE REVIEW

**Review by PavlosTze — CHANGES_REQUESTED** [review]
Some UI issues that I saw:
1. On the devices list (either cell or my devices) the chips should not be horizontally scrollable but the address should be trimmed with ellipsize (something relevant is left as a comment in Figma).
2. The WiFi icon feels a lot bigger than the Helium's one.
3. The status chips have wrong background color in the dark mode, they should have `successTint` and `errorTint` respectively.

**Comment by pantelisss** [comment]
@PavlosTze about the icon size, there is a significant difference in the designs too. I exported both of them from figma

**Review by PavlosTze — CHANGES_REQUESTED** [review]
Regarding the icon size let's see if we can figure it out somehow, because it looks bad at the moment. Also the chips should start from the start of the card (screenshot attached for both issues).
image

**Comment by pantelisss** [comment]
@PavlosTze the helium icon is updated

**Review by PavlosTze — APPROVED** [review]
Looks good! 👏

**Pull request merged**
