### PR TITLE
Stations rewards screen

### PR DESCRIPTION
**Pull request by pantelisss**
## **Why?**
Implementation of reward analytics screen
### **How?**
- The necessary implementation for the new API endpoints was added. (MeUseCse, MeRepository, etc)
- Added a new style for the `CustomSegmentView` (`compact`) to show date range picker (7D, 1M, 1Y)
- `RewardAnalyticsView` is the container of the new screen
  - `RewardAnalyticsViewModel` contains the logic
  - `ChartView` shows the charts that are rendered with SwiftUI native charts library
  - `RewardAnalyticsChartFactory` generates the data to show in charts
### **Testing**
Since the api implementation is not implemented yet, use the mock scheme (wxm-ios-mock) to run the app
### **Additional context**
fixes fe-1094

### CODE REVIEW

**Review by PavlosTze — CHANGES_REQUESTED** [review]
Some UI issues I encountered:
1. Τhe "Last Run" should be `+Χ,ΧΧ`, now it's `Χ,ΧΧ`.
2. The tooltip in the charts doesn't show any values, it's just an empty box.
3. The dataset mode in the charts should **not** be ``cubicBezier`, it should be `LINEAR`, as in the design the edges are sharp and not "rounded" (which is the solution bezier applies)
4. In the "rewards breakdown" chart, the purple color feels like it's the darker one, when it should be the lighter one.
5. In the "rewards breakdown" chart, the coloring is off for the base rewards, it's green when it should be the blue one, the `ChartsPrimary`.
6. In the "rewards breakdown" chart, the legends are missing below the chart.
7. In the "rewards breakdown" chart, I added a new entry in the `data` with `code=cell_reward` but it didn't show up in the chart. We should sum all unknown ones and show them up as "Others". 
8. The "Boost Period" is wrong, it should be in the format of "Feb 14 2025 - Apr 05 2026".
9. I added an error in the "1M" json for the rewards breakdown chart, but the error didn't show up in the card. I would expect there an error to be shown allowing the user to try a different period (e.g. select "7D") but not showing any chart or data info, because it "swallows" the error and feels like the data that are shown are correct.
10. Same as above applies for the "Total Earned" chart.
11. I added a new station in the `get_user_devices.json` and in the rewards screen it didn't show up. Instead I had a copy of "Station Name A" (and it was expanded as well, only the first card should be expanded).

**Comment by pantelisss** [comment]
> 11. I added a new station in the `get_user_devices.json` and in the rewards screen it didn't show up. Instead I had a copy of "Station Name A" (and it was expanded as well, only the first card should be expanded).

Seems that works with different devices. The issue with the copy is expected since the device ID is the way SwiftUI associates things

**Comment by pantelisss** [comment]
@PavlosTze is ready for testing. 
Keep in mind that I didn't implement something for the "Y max" task. I think the SwiftUI charts library handles these cases properly

**Comment by PavlosTze** [comment]
> @PavlosTze is ready for testing. Keep in mind that I didn't implement something for the "Y max" task. I think the SwiftUI charts library handles these cases properly

I wish I could say the same about Android😛 

Will have a look at this today or early morning tomorrow!

**Review by PavlosTze — CHANGES_REQUESTED** [review]
Good job @pantelisss , although I still found some issues (most are minor):
1. In both charts, a single point is not visible (on my end, last 7D is a single point dataset), we should enable `circle points` when the `dataSet.size == 1`
2. In both charts, the tooltip's date is off in 1M, it should be in the format "Sep 10" for example, but it's 09/10.
3. Same as above point, in the 1Y mode, the tooltip's date should fully show the month e.g. "September" instead of "Sep".
4. In both charts, the grid lines and the X axis feel "too black", I guess the colors are according the spec based on what I see, but can we decrease a bit their "size/width" ?
5. In both charts, when we are in the loading state we should hide the "Earned by this station" value (not the title itself, but the value only)
6. In both charts in some modes (e.g. 1M) the X axis labels do not respect the horizontal margin/padding and are very close to the edge of the card (or even touch it)
7. I think in the boost period there is an extra space after the `-`
9. In the "rewards breakdown" chart, the purple color feels like it's the darker one, when it should be the lighter one.
10. I added an error in the mock json for the rewards breakdown chart, but the error didn't show up in the card. (the error state is a new design available in Figma)
11. Same as above applies for the "Total Earned" chart. (the error state is a new design available in Figma)

**Comment by pantelisss** [comment]
@PavlosTze is ready for review
Everything is fixed except the issue with the grid line size, as we discussed

**Review by PavlosTze — CHANGES_REQUESTED** [review]
Great job Panteli, all issues got fixed except one very minor: 

1. In both charts, the tooltip date in the 7D should be `${3-letter month} $date` (e.g. Sep 10) instead of `$date ${3-letter-month}` (e.g. 10 Sep.(

**Comment by pantelisss** [comment]
> Great job Panteli, all issues got fixed except one very minor:
> 
> 1. In both charts, the tooltip date in the 7D should be `${3-letter month} $date` (e.g. Sep 10) instead of `$date ${3-letter-month}` (e.g. 10 Sep.)

It's because of localization. I've made a question for this in the feature's  slack channel.

**Review by PavlosTze — APPROVED** [review]

**Pull request merged**
